package syncintegration

import "errors"

var (
	errAuthorizationDecisionMismatch = errors.New("authorization decision reference does not match checkpoint request")
	errCheckpointAuthorizerRequired = errors.New("checkpoint authorizer is required")
	errCheckpointExecutorRequired = errors.New("checkpoint executor is required")
	errCheckpointFailureCategoryRequired = errors.New("failed checkpoint requires a bounded failure category")
	errCheckpointServiceNotInitialized = errors.New("checkpoint service is not initialized")
	errCheckpointStatusDatasetMismatch = errors.New("checkpoint status dataset ID does not match submission")
	errCheckpointStatusMustAdvance = errors.New("checkpoint status observation time must advance")
	errCheckpointStatusObservedTimeZero = errors.New("checkpoint status observation time must not be zero")
	errCheckpointStatusOperationMismatch = errors.New("checkpoint status operation ID does not match submission")
	errCheckpointStatusPredatesSubmission = errors.New("checkpoint status predates checkpoint submission")
	errCheckpointStatusRequestMismatch = errors.New("checkpoint status request ID does not match submission")
	errCheckpointStatusScopeMismatch = errors.New("checkpoint status Backup scope ID does not match submission")
	errCheckpointStoreNotInitialized = errors.New("checkpoint status store is not initialized")
	errCheckpointStoreNotRegularFile = errors.New("checkpoint status store must be a regular file")
	errCheckpointStorePathEmpty = errors.New("checkpoint status store path must not be empty")
	errCheckpointStorePathInvalid = errors.New("checkpoint status store path must identify a file")
	errCheckpointStorePermissions = errors.New("checkpoint status store permissions must not grant group or other access")
	errCheckpointSubmissionAcceptedAtZero = errors.New("checkpoint submission acceptance time must not be zero")
	errCheckpointSubmissionDatasetMismatch = errors.New("checkpoint submission dataset ID does not match request")
	errCheckpointSubmissionRequestMismatch = errors.New("checkpoint submission request ID does not match request")
	errCheckpointSubmissionScopeMismatch = errors.New("checkpoint submission Backup scope ID does not match resolved scope")
	errCompletedCheckpointFailureCategory = errors.New("completed checkpoint must not carry a failure category")
	errCompletedIntegrityEvidenceRegressed = errors.New("completed checkpoint integrity evidence must not regress")
	errCompletedRecoveryPointIDChanged = errors.New("completed checkpoint recovery point ID must not change")
	errCompletedRestoreEvidenceRegressed = errors.New("completed checkpoint restore evidence must not regress")
	errCompletedUsableEvidenceRegressed = errors.New("completed checkpoint usable evidence must not regress")
	errContextRequired = errors.New("context is required")
	errDatasetScopeResolverRequired = errors.New("dataset scope resolver is required")
	errEvaluationTimeZero = errors.New("evaluation time must not be zero")
	errFailedCheckpointRecoveryEvidence = errors.New("failed checkpoint must not claim a usable or verified recovery point")
	errMappingStoreNotInitialized = errors.New("dataset-scope mapping store is not initialized")
	errMappingStoreNotRegularFile = errors.New("dataset-scope mapping store must be a regular file")
	errMappingStorePathEmpty = errors.New("dataset-scope mapping store path must not be empty")
	errMappingStorePathInvalid = errors.New("dataset-scope mapping store path must identify a file")
	errMappingStorePermissions = errors.New("dataset-scope mapping store permissions must not grant group or other access")
	errMappingUpdateTimeZero = errors.New("mapping update time must not be zero")
	errResolvedMappingDatasetMismatch = errors.New("resolved mapping dataset ID does not match checkpoint request")
	errRestoreVerificationEvidenceIncomplete = errors.New("restore verification requires a usable integrity-verified recovery point")
	errTrailingJSONValue = errors.New("trailing JSON value is not permitted")
)
